### ISSUE TITLE
path names limit the number of characters to a small quantity

### ISSUE THREAD

**Issue by TricksterSam** [lar0sa/notes_lib#5]
If notes is used in a patch saved in a directory with a long path, it will crash Pd with a buffer overrun when attempting to render. More testing is needed, but observably a path with 83 characters crashes while one with 63 characters doesn't. Is there a 64 character limit?

**Comment by lar0sa** [comment]
I think Fede's (fch) last commit should solve this one by using t_atom paths[MAXPDSTRING];. can you test the latest source?

**Comment by lar0sa** [comment]
This should now be resolved. Please check.

**Comment by TricksterSam** [comment]
Oh, thanks! Missed your last email. I'll try it out.

**Comment by lar0sa** [comment]
Let me know if you find an error still!
